- commands.md
- db/migrations/20220509203931-create-user.js
- db/migrations/20220509203952-create-story.js
- db/migrations/20220509204000-create-comment.js
- db/migrations/20220509204006-create-like.js
- db/models/comment.js
- db/models/like.js
- db/models/story.js
- db/models/user.js
> Test branch

- routes/users.js
- views/user-login.pug
> LogIn Pug, LogIn Routes Added

- routes/users.js
> Took out the console.logs

- views/error.pug
- views/register.pug
- views/user-login.pug
changed error.pug so it could properly display errors
> added error display for login and register pages

- app.js
- commands.md
- db/migrations/20220509203952-create-story.js
- db/models/story.js
- db/seeders/20220510173322-users.js
- db/seeders/20220510173816-stories.js
- package.json
- routes/stories.js
> Created seed data files and created stories routes

- routes/users.js
- views/layout.pug
> Implemented Logout and Navigation Bar Added

- routes/users.js
- views/user-login.pug
> added demo user

- db/seeders/20220510173322-users.js
- routes/stories.js
- views/stories.pug
stories and hashed password seeders
> stories and hashed password seeders

- app.js
- db/models/story.js
- db/models/user.js
- routes/stories.js
- views/stories.pug
- views/story.pug
> Finished GET all stories and GET story by id

- routes/stories.js
- views/storyDelete.pug
Finished Routes delete and added a pug template. Please approve
> Finished Routes delete and added a pug template

- routes/comments.js
- routes/stories.js
- views/story.pug
> comments almost done just missing edit button

- views/layout.pug
- views/stories.pug
> edited some pug

- public/stylesheets/register.css
- views/register.pug
> css for register

- public/stylesheets/login.css
- views/user-login.pug
login styles. The red part is me adding a class. All pug code functionality is the same.
> login styles

- public/stylesheets/login.css
- views/user-login.pug
> added header

- public/javascripts/index.js
- public/stylesheets/story.css
- routes/comments.js
- views/story.pug
DONE WITH COMMMEEMEMMEMEMEMEENNTSSSS!!!!!
> Comments denis

- public/stylesheets/storyEdit.css
- views/storyEdit.pug
> styles for story edit

- public/stylesheets/storyDelete.css
- views/storyDelete.pug
> styles for deleting stories

- views/story.pug
Please approve after reviewing
> Only let users edit and delete their own posts

- public/javascripts/index.js
- public/stylesheets/story.css
- views/story.pug
> Changed icons and positioning of likes

- public/stylesheets/login.css
> fixed sign up clickable area

- views/storyEdit.pug
fixed autofull content when editing a story
> fixed autofull content when editing a story

- public/stylesheets/story.css
- routes/stories.js
- views/story.pug
> Icon stays the same when page is refreshed

- public/stylesheets/register.css
- views/register.pug
> FINALLY! IT LOOKS OKAY!

- db/seeders/20220510173816-stories.js
> added story seeder data

- routes/stories.js
> Redirect to Log-in

- routes/stories.js
- views/index.pug
- views/story.pug
> Added redirect for reading button

- routes/index.js
- views/index.pug
added redirect for bottom button
> Redirects with See more articles button
